name: Build & Push Docker image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  DOCKERHUB_REPO: lonord/easy-chat

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Decide build ref and image tag
        id: vars
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            raw_tag="${GITHUB_REF#refs/tags/}"   # v1.2
            version="${raw_tag#v}"               # 1.2
            echo "build_ref=${GITHUB_REF}" >> $GITHUB_OUTPUT
            echo "image_tag=${version}" >> $GITHUB_OUTPUT
          else
            echo "build_ref=refs/heads/main" >> $GITHUB_OUTPUT
            echo "image_tag=latest" >> $GITHUB_OUTPUT
          fi
          echo "Chosen build_ref=$(grep build_ref $GITHUB_OUTPUT | cut -d= -f2)"
          echo "Chosen image_tag=$(grep image_tag $GITHUB_OUTPUT | cut -d= -f2)"

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.vars.outputs.build_ref }}

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: docker.io/${{ env.DOCKERHUB_REPO }}:${{ steps.vars.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
